// src/app/data/turkish-cities-with-districts.ts
export const TURKISH_CITIES_WITH_DISTRICTS: { [city: string]: string[] } = {
  'Adana':           ['Seyhan',    'Çukurova',   'Yüreğir',    'Sarıçam',   'Ceyhan'],
  'Adıyaman':        ['Merkez',    'Kahta',      'Besni',      'Gölbaşı',   'Samsat'],
  'Afyonkarahisar':  ['Merkez',    'Sandıklı',   'İscehisar',  'Bolvadin',  'Dinar'],
  'Ağrı':            ['Merkez',    'Doğubayazıt','Patnos',     'Diyadin',   'Eleşkirt'],
  'Amasya':          ['Merkez',    'Merzifon',   'Suluova',    'Gümüşhacıköy','Taşova'],
  'Ankara':          ['Çankaya',   'Keçiören',   'Yenimahalle','Mamak',     'Altındağ'],
  'Antalya':         ['Muratpaşa', 'Kepez',      'Konyaaltı',  'Alanya',    'Manavgat'],
  'Artvin':          ['Merkez',    'Hopa',       'Borçka',     'Arhavi',    'Murgul'],
  'Aydın':           ['Merkez',    'Efeler',     'Nazilli',    'Kușadası',  'Didim'],
  'Balıkesir':       ['Merkez',    'Karesi',     'Altıeylül',  'Edremit',   'Bandırma'],
  'Bilecik':         ['Merkez',    'Osmaneli',   'Bozüyük',    'Gölpazarı', 'İnhisar'],
  'Bingöl':          ['Merkez',    'Genç',       'Solhan',     'Kiğı',      'Yayladere'],
  'Bitlis':          ['Merkez',    'Tatvan',     'Ahlat',      'Güroymak',  'Hizan'],
  'Bolu':            ['Merkez',    'Gerede',     'Mudurnu',    'Dörtdivan', 'Yeniçağa'],
  'Burdur':          ['Merkez',    'Gölhisar',   'Çavdır',     'Yeşilova',  'Tefenni'],
  'Bursa':           ['Osmangazi', 'Yıldırım',   'Nilüfer',    'İnegöl',    'Gemlik'],
  'Çanakkale':       ['Merkez',    'Gelibolu',   'Eceabat',    'Lapseki',   'Biga'],
  'Çankırı':         ['Merkez',    'Çerkeş',     'Orta',       'Eldivan',   'Kurşunlu'],
  'Çorum':           ['Merkez',    'Osmancık',   'Uğurludağ',  'Sungurlu',  'Bayat'],
  'Denizli':         ['Merkez',    'Pamukkale',  'Çivril',     'Tavas',     'Buldan'],
  'Diyarbakır':      ['Merkez',    'Bağlar',     'Kayapınar',  'Yenişehir', 'Bismil'],
  'Edirne':          ['Merkez',    'Keşan',      'Uzunköprü',  'Meriç',     'İpsala'],
  'Elazığ':          ['Merkez',    'Karakoçan',  'Maden',      'Kovancılar','Arıcak'],
  'Erzincan':        ['Merkez',    'Tercan',     'Kemah',      'İliç',      'Refahiye'],
  'Erzurum':         ['Merkez',    'Yakutiye',   'Palandöken', 'Aziziye',   'Oltu'],
  'Eskişehir':       ['Merkez',    'Tepebaşı',   'Odunpazarı', 'Seyitgazi', 'Mahmudiye'],
  'Gaziantep':       ['Şahinbey',  'Şehitkamil', 'Nizip',      'Oğuzeli',   'İslahiye'],
  'Giresun':         ['Merkez',    'Bulancak',   'Espiye',     'Görele',    'Eynesil'],
  'Gümüşhane':       ['Merkez',    'Kelkit',     'Şiran',      'Torul',     'Köse'],
  'Hakkâri':         ['Merkez',    'Yüksekova',  'Şemdinli',   'Çukurca',   'Konaklı'],
  'Hatay':           ['Antakya',   'İskenderun', 'Defne',      'Dörtyol',   'Reyhanlı'],
  'Isparta':         ['Merkez',    'Eğirdir',    'Yalvaç',     'Senirkent', 'Sütçüler'],
  'Mersin':          ['Yenişehir', 'Mezitli',    'Tarsus',     'Erdemli',   'Silifke'],
  'İstanbul':        ['Fatih',     'Kadıköy',    'Beşiktaş',   'Üsküdar',   'Bakırköy'],
  'İzmir':           ['Konak',     'Karşıyaka',  'Bornova',    'Buca',      'Gaziemir'],
  'Kars':            ['Merkez',    'Sarıkamış',  'Kağızman',   'Digor',     'Arpaçay'],
  'Kastamonu':       ['Merkez',    'Taşköprü',   'İnebolu',    'Cide',      'Abana'],
  'Kayseri':         ['Melikgazi', 'Kocasinan',  'Talas',      'Develi',    'Hacılar'],
  'Kırklareli':      ['Merkez',    'Lüleburgaz', 'Pehlivanköy','Kofçaz',    'Pınarhisar'],
  'Kırşehir':        ['Merkez',    'Mucur',      'Çiçekdağı',  'Kaman',     'Akpınar'],
  'Kilis':           ['Merkez',    'Elbeyli',    'Musabeyli',  'Polateli',  'Marashimşekeroğlu'],
  'Kocaeli':         ['İzmit',     'Gebze',      'Gölcük',     'Başiskele', 'Derince'],
  'Konya':           ['Selçuklu',  'Karatay',    'Meram',      'Ereğli',    'Ilgın'],
  'Kütahya':         ['Merkez',    'Simav',      'Gediz',      'Emet',      'Tavşanlı'],
  'Malatya':         ['Merkez',    'Battalgazi', 'Yeşilyurt',  'Akçadağ',   'Darende'],
  'Manisa':          ['Merkez',    'Şehzadeler', 'Yunusemre',  'Turgutlu',  'Salihli'],
  'Kahramanmaraş':   ['Merkez',    'Onikişubat', 'Dulkadiroğlu','Elbistan', 'Pazarcık'],
  'Mardin':          ['Merkez',    'Artuklu',    'Nusaybin',   'Kızıltepe', 'Midyat'],
  'Muğla':           ['Merkez',    'Bodrum',     'Marmaris',   'Fethiye',   'Datça'],
  'Muş':             ['Merkez',    'Malazgirt',  'Bulanık',    'Hasköy',    'Varto'],
  'Nevşehir':        ['Merkez',    'Ürgüp',      'Avanos',     'Gülşehir',  'Derinkuyu'],
  'Niğde':           ['Merkez',    'Bor',        'Çiftlik',    'Ulukışla',  'Altunhisar'],
  'Ordu':            ['Merkez',    'Altınordu',  'Fatsa',      'Perşembe',  'Ünye'],
  'Rize':            ['Merkez',    'Çayeli',     'Pazar',      'Ardeşen',   'Fındıklı'],
  'Sakarya':         ['Merkez',    'Adapazarı',  'Serdivan',   'Erenler',   'Karasu'],
  'Samsun':          ['Merkez',    'Atakum',     'Canik',      'İlkadım',   'Bafra'],
  'Siirt':           ['Merkez',    'Pervari',    'Şirvan',     'Baykan',    'Kurtalan'],
  'Sinop':           ['Merkez',    'Boyabat',    'Durağan',    'Türkeli',   'Gerze'],
  'Sivas':           ['Merkez',    'Yıldızeli',  'Divriği',    'Şarkışla',  'Kangal'],
  'Tekirdağ':        ['Merkez',    'Süleymanpaşa','Çorlu',     'Malkara',   'Muratlı'],
  'Tokat':           ['Merkez',    'Erbaa',      'Turhal',     'Niksar',    'Almus'],
  'Trabzon':         ['Merkez',    'Ortahisar',  'Beşikdüzü',  'Akçaabat',  'Tonya'],
  'Tunceli':         ['Merkez',    'Mazgirt',    'Nazımiye',   'Ovacık',    'Pertek'],
  'Şanlıurfa':       ['Merkez',    'Eyyübiye',   'Haliliye',   'Karaköprü', 'Suruç'],
  'Uşak':            ['Merkez',    'Banaz',      'Eşme',       'Ulubey',    'Sivaslı'],
  'Van':             ['Merkez',    'İpekyolu',   'Edremit',    'Tuşba',     'Erciş'],
  'Yozgat':          ['Merkez',    'Akdağmadeni','Boğazlıyan', 'Sorgun',    'Sarıkaya'],
  'Zonguldak':       ['Merkez',    'Ereğli',     'Çaycuma',    'Devrek',    'Kilimli'],
  'Aksaray':         ['Merkez',    'Eskil',      'Güzelyurt',  'Ortaköy',   'Sarıyahşi'],
  'Bayburt':         ['Merkez',    'Aydıntepe',  'Demirözü',   'Karşıyaka', 'Çiğdem'],
  'Karaman':         ['Merkez',    'Ermenek',    'Başyayla',   'Kazımkarabekir','Ayrancı'],
  'Kırıkkale':       ['Merkez',    'Yahşihan',   'Delice',     'Karakeçili','Sulakyurt'],
  'Batman':          ['Merkez',    'Kozluk',     'Sason',      'Beşiri',    'Gercüş'],
  'Şırnak':          ['Merkez',    'Cizre',      'Silopi',     'İdil',      'Uludere'],
  'Bartın':          ['Merkez',    'Kurucaşile', 'Ulus',       'Amasra',    'Abana'],
  'Ardahan':         ['Merkez',    'Çıldır',     'Göle',       'Posof',     'Damal'],
  'Iğdır':           ['Merkez',    'Tuzluca',    'Aralık',     'Karakoyunlu','Halfeli'],
  'Yalova':          ['Merkez',    'Çınarcık',   'Termal',     'Altınova',  'Armutlu'],
  'Karabük':         ['Merkez',    'Safranbolu', 'Eskipazar',  'Ovacık',    'Yenice']
};